# Generated by Django 3.1.7 on 2021-04-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210402_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquote',
            name='gallons',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fuelquote',
            name='suggested_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fuelquote',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
